# SPDX-FileCopyrightText: 2024 Amgen
#
# SPDX-License-Identifier: BSD-3-Clause

version: "2"         # required to adjust maintainability checks

# checks:
#   argument-count:
#     enabled: true
#     config:
#       threshold: 5
#   complex-logic:
#     enabled: true
#     config:
#       threshold: 5
#   file-lines:
#     enabled: true
#     config:
#       threshold: 250
#   method-complexity:
#     enabled: true
#     config:
#       threshold: 5
#   method-count:
#     enabled: true
#     config:
#       threshold: 20
#   method-lines:
#     enabled: true
#     config:
#       threshold: 25
#   nested-control-flow:
#     enabled: true
#     config:
#       threshold: 4
#   return-statements:
#     enabled: true
#     config:
#       threshold: 4
#   similar-code:
#     enabled: true
#     config:
#       threshold: 32 #language-specific defaults. overrides affect all languages.
#   identical-code:
#     enabled: true
#     config:
#       threshold: 32 #language-specific defaults. overrides affect all languages.

plugins:
  sonar-python:
    enabled: true
    # issue_override:
    #   severity: critical   #for setting the level major,minor,blocker,critical
  # eslint:
  #   enabled: false
  #   checks:
  #     complexity:
  #       enabled: true
  #   config:
  #     extensions:
  #     - .es6
  #     - .js
  #     - .jsx
  #     - .mjs
      # - .tsx
      # - .scss
  #     - .vue

#exclude_patterns:
# - "frontend/"
#- "code/"
#- "gumps/"
#- "presentations/"
#- "tests/"
#- "img"
# - "dist/"
# - "features/"
# - "**/node_modules/"
# - "script/"
# - "**/spec/"
# - "**/test/"
# - "**/tests/"
# - "Tests/"
# - "**/vendor/"
# - "**/*_test.go"
# - "**/*.d.ts"
