#SPDX-FileCopyrightText: 2024 Amgen
#SPDX-License-Identifier: BSD-3-Clause

name: gumps_gpu_311
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - blas=*=*mkl
  - mkl~=2024.0.0
  - attrs~=23.2.0
  - openpyxl~=3.1.2
  - numpy~=1.26.3
  - pandas~=2.2.0
  - pyarrow~=14.0.2
  - scipy~=1.12.0
  - cvxopt~=1.3.2
  - git~=2.43.0
  - networkx~=3.2.1
  - salib~=1.4.7
  - mypy~=1.8.0
  - pylint~=3.0.3
  - pytest~=8.0.0
  - pytest-xdist~=3.5.0
  - pytest-cov~=4.1.0
  - filelock~=3.13.1
  - h5py~=3.10.0
  - addict~=2.4.0
  - ipykernel~=6.29.0
  - pymoo~=0.6.1.1
  - coverage~=7.4.1
  - typing_extensions~=4.9.0
  - seaborn~=0.13.2
  - corner~=2.2.2
  - arviz~=0.17.0
  - scikit-learn~=1.3.0
  - joblib~=1.3.2
  - pint~=0.23
  - optuna~=3.4.0
  - lightning~=2.1.3
  - tensorboard~=2.15.1
  - py-xgboost-cpu~=2.0.3
  - multiprocess~=0.70.16
  - pytorch~=2.0.0
  - pytorch-cuda=11.8
